typography_spectrum: 0.36271017766557634
color:
  brandStrength: 0.5693510677665472
  lightness: 0.2267446822952479
  saturation: 0.10479574929922819
  rhythmicContrast: 0.28372457437217236
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.2283091084100306
name: Thor Photos
title: Last Best Place
description: Montana
